import fs from "node:fs";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import http from "node:http";
import { setTimeout as wait } from "node:timers/promises";
const cwd=new URL(".",import.meta.url).pathname.replace(/^\/(.:)/,"$1"),port=18116,fixturePort=18117;
const child=spawn(process.execPath,["server.mjs"],{cwd,env:{...process.env,NC11_PORT:String(port),NC11_INACTIVITY_KICK_MS:"1200"},stdio:"pipe"});let log="";child.stdout.on("data",b=>log+=b);child.stderr.on("data",b=>log+=b);
for(let i=0;i<100;i++){try{if((await fetch(`http://127.0.0.1:${port}/health`,{signal:AbortSignal.timeout(100)})).ok)break;}catch{}if(i===99)throw new Error(log);await wait(50);}
const fixture=http.createServer((req,res)=>{res.setHeader("Content-Type","text/html");res.end('<!doctype html><html><body><input id="username" value="Player"></body></html>');});await new Promise(r=>fixture.listen(fixturePort,"127.0.0.1",r));
const require=createRequire("C:/Users/super/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json"),{chromium}=require("playwright"),source=fs.readFileSync(new URL("nitroclash-local-11v11.user.js",import.meta.url),"utf8").replace("wss://one1v11.onrender.com",`ws://127.0.0.1:${port}`),browser=await chromium.launch({channel:"msedge",headless:true});
try{const context=await browser.newContext({viewport:{width:1280,height:720},permissions:["local-network-access"]});await context.addInitScript(source);const idle=await context.newPage(),active=await context.newPage();await Promise.all([idle.goto(`http://127.0.0.1:${fixturePort}`),active.goto(`http://127.0.0.1:${fixturePort}`)]);await idle.locator("#username").fill("IdlePlayer");await active.locator("#username").fill("ActivePlayer");await idle.locator("#nc11-play").click();await active.locator("#nc11-play").click();await active.waitForFunction(()=>document.querySelector("#nc11-info")?.textContent.includes("PLAYING"));await active.keyboard.down("d");await idle.waitForSelector("#nc11-end.nc11-kicked",{timeout:5000});assert.equal(await idle.locator("#nc11-end h2").innerText(),"You have been kicked out for inactivity.");assert.equal(await idle.locator("#nc11-kicked-home").innerText(),"Back to homepage");await idle.screenshot({path:new URL("visual-test-v30-inactivity-kick.png",import.meta.url).pathname.replace(/^\/(.:)/,"$1")});await active.keyboard.down("Tab");await active.waitForFunction(()=>getComputedStyle(document.querySelector("#nc11-board")).display==="block");const board=await active.locator("#nc11-board").innerText();assert.equal(board.includes("IdlePlayer"),false);await active.keyboard.up("Tab");await active.keyboard.up("d");console.log("PASS real Edge inactivity modal and cross-client roster removal");}finally{await browser.close();fixture.close();child.kill();}
